### ISSUE TITLE
Subtask zu #63 Bericht Docu: Use-Case 

### ISSUE THREAD

**Issue by Julian19E** [jerdbaer/Zeiterfassung#79]
Für den Projektbericht sollen die Use-Case nochmal Überarbeitet werden. 
Als "Vorlagen" wird die Power Point "Themenvorstellung Java" und "User Storties Zeiterfassung Josi" genutzt. 

Es sind für die Bearbeitung des Tickets folgende ToDos zu erledige:

- [ ] Ablauf des Einlogens ins System 
- [ ] Ablauf des Eintragens dereinzelnen Stunden
- [ ] Verarbeitung ggf. Ausgabe der Stunden für den Mitarbeiter
