### ISSUE TITLE
Subtask zu #63 Bericht Docu: Tests 

### ISSUE THREAD

**Issue by Julian19E** [jerdbaer/Zeiterfassung#85]
Für die Projektdokumentation sollen Test im Quellcode als auch im Testprotokoll erfolgen.
Im Test sollen folgende Kriterien enthalten sein. (Abdeckung, Vollständigkeit und Dokumentation)

Folgende AC sind zu erledigen: 

- [ ] Teste einzelner Methoden auf Funktionalität
- [ ] Validierungen im User Interface bezogen auf die Eingaben/Ausgaben
- [ ] (Prüfung der Dokumentation auf Inhaltliche Angaben) ???
